// Main Dashboard
f = figure( ...
    "figure_name", "PCB Mentor", ...
    "figure_position", [80 40], ...
    "axes_size", [1200 720], ...
    "backgroundcolor", [0.94 0.96 0.98], ...
    "menubar", "none", ...
    "toolbar", "none", ...
    "resize", "off");

// LEFT NAVIGATION
nav = uicontrol(f, ...
    "style", "frame", ...
    "position", [0 0 250 720], ...
    "backgroundcolor", [0.08 0.18 0.30]);

// Application title
uicontrol(nav, ...
    "style", "text", ...
    "position", [25 645 200 45], ...
    "string", "PCB Mentor", ...
    "fontsize", 24, ...
    "fontweight", "bold", ...
    "foregroundcolor", [1 1 1], ...
    "backgroundcolor", [0.08 0.18 0.30]);

uicontrol(nav, ...
    "style", "text", ...
    "position", [25 615 200 25], ...
    "string", "PCB Design Learning Lab", ...
    "fontsize", 11, ...
    "foregroundcolor", [0.75 0.85 0.92], ...
    "backgroundcolor", [0.08 0.18 0.30]);

// Navigation buttons
uicontrol(nav, ...
    "style", "pushbutton", ...
    "position", [20 545 210 45], ...
    "string", "Dashboard", ...
    "fontsize", 13, ...
    "callback", "close(winsid()); exec(""gui/dashboard.sce"",-1)");

uicontrol(nav, ...
    "style", "pushbutton", ...
    "position", [20 490 210 45], ...
    "string", "Trace Width", ...
    "fontsize", 13, ...
    "callback", "close(winsid()); exec(""gui/tracewidth.sce"",-1)");

uicontrol(nav, ...
    "style", "pushbutton", ...
    "position", [20 435 210 45], ...
    "string", "Voltage Drop", ...
    "fontsize", 13, ...
    "callback", "close(winsid()); exec(""gui/voltage.sce"",-1)");

uicontrol(nav, ...
    "style", "pushbutton", ...
    "position", [20 380 210 45], ...
    "string", "DRC Assistant", ...
    "fontsize", 13, ...
    "callback", "close(winsid()); exec(""gui/drc.sce"",-1)");

uicontrol(nav, ...
    "style", "pushbutton", ...
    "position", [20 325 210 45], ...
    "string", "Footprint Guide", ...
    "fontsize", 13, ...
    "callback", "close(winsid()); exec(""gui/footprints.sce"",-1)");

uicontrol(nav, ...
    "style", "pushbutton", ...
    "position", [20 270 210 45], ...
    "string", "Learn PCB", ...
    "fontsize", 13, ...
    "callback", "close(winsid()); exec(""gui/learning.sce"",-1)");

// MAIN AREA
uicontrol(f, ...
    "style", "text", ...
    "position", [290 625 850 50], ...
    "string", "Welcome to PCB Mentor", ...
    "fontsize", 27, ...
    "fontweight", "bold", ...
    "foregroundcolor", [0.08 0.18 0.30], ...
    "backgroundcolor", [0.94 0.96 0.98]);

uicontrol(f, ...
    "style", "text", ...
    "position", [295 585 800 30], ...
    "string", "Interactive tools for understanding practical PCB design decisions.", ...
    "fontsize", 14, ...
    "foregroundcolor", [0.30 0.38 0.45], ...
    "backgroundcolor", [0.94 0.96 0.98]);

// INTRO CARD
intro = uicontrol(f, ...
    "style", "frame", ...
    "position", [290 430 850 130], ...
    "backgroundcolor", [1 1 1]);

uicontrol(intro, ...
    "style", "text", ...
    "position", [25 75 790 30], ...
    "string", "Design. Calculate. Visualize.", ...
    "fontsize", 20, ...
    "fontweight", "bold", ...
    "foregroundcolor", [0.05 0.35 0.55], ...
    "backgroundcolor", [1 1 1]);

uicontrol(intro, ...
    "style", "text", ...
    "position", [25 30 790 40], ...
    "string", ...
    ["Explore trace dimensions, voltage drop, design-rule checks,";
     "component footprints and PCB fundamentals."], ...
    "fontsize", 13, ...
    "foregroundcolor", [0.25 0.30 0.35], ...
    "backgroundcolor", [1 1 1]);

// QUICK ACTION CARDS
uicontrol(f, ...
    "style", "text", ...
    "position", [295 390 400 30], ...
    "string", "Quick Access", ...
    "fontsize", 18, ...
    "fontweight", "bold", ...
    "foregroundcolor", [0.08 0.18 0.30], ...
    "backgroundcolor", [0.94 0.96 0.98]);

// Card 1
c1 = uicontrol(f, ...
    "style", "frame", ...
    "position", [290 225 260 145], ...
    "backgroundcolor", [1 1 1]);

uicontrol(c1, ...
    "style", "text", ...
    "position", [15 95 230 30], ...
    "string", "TRACE WIDTH", ...
    "fontsize", 15, ...
    "fontweight", "bold", ...
    "foregroundcolor", [0.05 0.35 0.55], ...
    "backgroundcolor", [1 1 1]);

uicontrol(c1, ...
    "style", "text", ...
    "position", [15 55 230 30], ...
    "string", "Estimate current-carrying width.", ...
    "fontsize", 11, ...
    "backgroundcolor", [1 1 1]);

uicontrol(c1, ...
    "style", "pushbutton", ...
    "position", [15 15 230 30], ...
    "string", "Open Simulator", ...
    "callback", "close(winsid()); exec(""gui/tracewidth.sce"",-1)");

// Card 2
c2 = uicontrol(f, ...
    "style", "frame", ...
    "position", [570 225 260 145], ...
    "backgroundcolor", [1 1 1]);

uicontrol(c2, ...
    "style", "text", ...
    "position", [15 95 230 30], ...
    "string", "VOLTAGE DROP", ...
    "fontsize", 15, ...
    "fontweight", "bold", ...
    "foregroundcolor", [0.05 0.35 0.55], ...
    "backgroundcolor", [1 1 1]);

uicontrol(c2, ...
    "style", "text", ...
    "position", [15 55 230 30], ...
    "string", "Study resistance and power loss.", ...
    "fontsize", 11, ...
    "backgroundcolor", [1 1 1]);

uicontrol(c2, ...
    "style", "pushbutton", ...
    "position", [15 15 230 30], ...
    "string", "Open Simulator", ...
    "callback", "close(winsid()); exec(""gui/voltage.sce"",-1)");

// Card 3
c3 = uicontrol(f, ...
    "style", "frame", ...
    "position", [850 225 290 145], ...
    "backgroundcolor", [1 1 1]);

uicontrol(c3, ...
    "style", "text", ...
    "position", [15 95 260 30], ...
    "string", "DESIGN CHECK", ...
    "fontsize", 15, ...
    "fontweight", "bold", ...
    "foregroundcolor", [0.05 0.35 0.55], ...
    "backgroundcolor", [1 1 1]);

uicontrol(c3, ...
    "style", "text", ...
    "position", [15 55 260 30], ...
    "string", "Explore common PCB rule violations.", ...
    "fontsize", 11, ...
    "backgroundcolor", [1 1 1]);

uicontrol(c3, ...
    "style", "pushbutton", ...
    "position", [15 15 260 30], ...
    "string", "Open DRC", ...
    "callback", "close(winsid()); exec(""gui/drc.sce"",-1)");

// TIP
tip = uicontrol(f, ...
    "style", "frame", ...
    "position", [290 65 850 130], ...
    "backgroundcolor", [0.88 0.94 0.98]);

uicontrol(tip, ...
    "style", "text", ...
    "position", [20 80 150 30], ...
    "string", "PCB TIP", ...
    "fontsize", 14, ...
    "fontweight", "bold", ...
    "foregroundcolor", [0.05 0.35 0.55], ...
    "backgroundcolor", [0.88 0.94 0.98]);

uicontrol(tip, ...
    "style", "text", ...
    "position", [20 35 790 40], ...
    "string", ...
    ["A wider copper trace generally reduces resistance and";
     "voltage drop, but board space and manufacturing limits matter."], ...
    "fontsize", 12, ...
    "backgroundcolor", [0.88 0.94 0.98]);

// Footer
uicontrol(f, ...
    "style", "text", ...
    "position", [25 15 200 25], ...
    "string", "GUIVerse 2026", ...
    "fontsize", 10, ...
    "foregroundcolor", [0.75 0.85 0.92], ...
    "backgroundcolor", [0.08 0.18 0.30]);
