//PCB Learning WIndow
global topicTitle topicText
global topicBtn1 topicBtn2 topicBtn3 topicBtn4 topicBtn5
//Main Window 
f = figure( ...
    "figure_name", "PCB Mentor - Learn PCB", ...
    "figure_position", [120 70], ...
    "axes_size", [1050 650], ...
    "backgroundcolor", [0.94 0.96 0.98], ...
    "menubar", "none", ...
    "toolbar", "none", ...
    "resize", "off");
//Header
uicontrol(f, ...
    "style", "text", ...
    "position", [35 580 900 45], ...
    "string", "Learn PCB Design", ...
    "fontsize", 26, ...
    "fontweight", "bold", ...
    "foregroundcolor", [0.08 0.18 0.30], ...
    "backgroundcolor", [0.94 0.96 0.98], ...
    "horizontalalignment", "left");
uicontrol(f, ...
    "style", "text", ...
    "position", [35 545 900 25], ...
    "string", "Quick reference for common PCB design concepts", ...
    "fontsize", 12, ...
    "foregroundcolor", [0.35 0.40 0.45], ...
    "backgroundcolor", [0.94 0.96 0.98], ...
    "horizontalalignment", "left");
//Topic Panel
uicontrol(f, ...
    "style", "text", ...
    "position", [35 505 250 25], ...
    "string", "TOPICS", ...
    "fontsize", 13, ...
    "fontweight", "bold", ...
    "foregroundcolor", [0.08 0.18 0.30], ...
    "backgroundcolor", [0.94 0.96 0.98], ...
    "horizontalalignment", "left");
//Topic Buttons
topicBtn1 = uicontrol(f, ...
    "style", "pushbutton", ...
    "position", [35 440 250 45], ...
    "string", "Trace Width", ...
    "fontsize", 12, ...
    "callback", "show_topic(1)");

topicBtn2 = uicontrol(f, ...
    "style", "pushbutton", ...
    "position", [35 385 250 45], ...
    "string", "Ground Plane", ...
    "fontsize", 12, ...
    "callback", "show_topic(2)");

topicBtn3 = uicontrol(f, ...
    "style", "pushbutton", ...
    "position", [35 330 250 45], ...
    "string", "Decoupling Capacitor", ...
    "fontsize", 12, ...
    "callback", "show_topic(3)");

topicBtn4 = uicontrol(f, ...
    "style", "pushbutton", ...
    "position", [35 275 250 45], ...
    "string", "Via", ...
    "fontsize", 12, ...
    "callback", "show_topic(4)");

topicBtn5 = uicontrol(f, ...
    "style", "pushbutton", ...
    "position", [35 220 250 45], ...
    "string", "PCB Clearance", ...
    "fontsize", 12, ...
    "callback", "show_topic(5)");

// CONTENT PANEL
content = uicontrol(f, ...
    "style", "frame", ...
    "position", [325 150 680 350], ...
    "backgroundcolor", [1 1 1]);

// Topic title
topicTitle = uicontrol(content, ...
    "style", "text", ...
    "position", [25 285 620 40], ...
    "string", "Trace Width", ...
    "fontsize", 21, ...
    "fontweight", "bold", ...
    "foregroundcolor", [0.05 0.35 0.55], ...
    "backgroundcolor", [1 1 1], ...
    "horizontalalignment", "left");

// Small separator
uicontrol(content, ...
    "style", "frame", ...
    "position", [25 275 610 2], ...
    "backgroundcolor", [0.85 0.88 0.91]);

// Description
topicText = uicontrol(content, ...
    "style", "text", ...
    "position", [25 75 610 185], ...
    "string", "Trace width determines the cross-sectional area of copper.", ...
    "fontsize", 13, ...
    "foregroundcolor", [0.18 0.20 0.23], ...
    "backgroundcolor", [1 1 1], ...
    "horizontalalignment", "left");

// TIP BOX
uicontrol(f, ...
    "style", "text", ...
    "position", [325 95 680 35], ...
    "string", "TIP: Select a topic to view its key design considerations.", ...
    "fontsize", 11, ...
    "foregroundcolor", [0.35 0.40 0.45], ...
    "backgroundcolor", [0.94 0.96 0.98], ...
    "horizontalalignment", "left");

// BACK BUTTON
uicontrol(f, ...
    "style", "pushbutton", ...
    "position", [35 100 250 45], ...
    "string", "Back to Dashboard", ...
    "fontsize", 12, ...
    "callback", "close(winsid()); exec(""gui/dashboard.sce"",-1)");

function show_topic(index)

    global topicTitle topicText
    global topicBtn1 topicBtn2 topicBtn3 topicBtn4 topicBtn5

    NL = ascii(10);

    if index == 1 then

        titleText = "Trace Width";

        body = ...
        "Trace width determines how much current a PCB" + NL + ...
        "trace can safely carry." + NL + NL + ...
        "A wider trace generally has lower resistance." + NL + ...
        "It depends mainly on current, copper thickness" + NL + ...
        "and allowable temperature rise.";


    elseif index == 2 then

        titleText = "Ground Plane";

        body = ...
        "A ground plane provides a low-impedance return" + NL + ...
        "path for current." + NL + NL + ...
        "It can reduce noise, loop area and EMI." + NL + ...
        "A continuous ground plane is generally preferred.";


    elseif index == 3 then

        titleText = "Decoupling Capacitor";

        body = ...
        "A decoupling capacitor provides local charge" + NL + ...
        "for an IC during fast current changes." + NL + NL + ...
        "Place it close to the IC power pins." + NL + ...
        "Short connections improve its effectiveness.";


    elseif index == 4 then

        titleText = "Via";

        body = ...
        "A via connects copper between PCB layers." + NL + NL + ...
        "Important parameters include drill diameter," + NL + ...
        "pad diameter and annular ring." + NL + NL + ...
        "Vias are commonly used for layer transitions.";


    else

        titleText = "PCB Clearance";

        body = ...
        "Clearance is the spacing between conductive" + NL + ...
        "features that are not electrically connected." + NL + NL + ...
        "It helps prevent shorts and manufacturing issues." + NL + ...
        "Always follow the PCB manufacturer rules.";

    end


    set(topicTitle, "string", titleText);
    set(topicText, "string", body);


    // Reset buttons

    set(topicBtn1, "backgroundcolor", [0.94 0.94 0.94]);
    set(topicBtn1, "foregroundcolor", [0 0 0]);

    set(topicBtn2, "backgroundcolor", [0.94 0.94 0.94]);
    set(topicBtn2, "foregroundcolor", [0 0 0]);

    set(topicBtn3, "backgroundcolor", [0.94 0.94 0.94]);
    set(topicBtn3, "foregroundcolor", [0 0 0]);

    set(topicBtn4, "backgroundcolor", [0.94 0.94 0.94]);
    set(topicBtn4, "foregroundcolor", [0 0 0]);

    set(topicBtn5, "backgroundcolor", [0.94 0.94 0.94]);
    set(topicBtn5, "foregroundcolor", [0 0 0]);


    // Highlight selected topic

    if index == 1 then
        set(topicBtn1, "backgroundcolor", [0.05 0.35 0.55]);
        set(topicBtn1, "foregroundcolor", [1 1 1]);

    elseif index == 2 then
        set(topicBtn2, "backgroundcolor", [0.05 0.35 0.55]);
        set(topicBtn2, "foregroundcolor", [1 1 1]);

    elseif index == 3 then
        set(topicBtn3, "backgroundcolor", [0.05 0.35 0.55]);
        set(topicBtn3, "foregroundcolor", [1 1 1]);

    elseif index == 4 then
        set(topicBtn4, "backgroundcolor", [0.05 0.35 0.55]);
        set(topicBtn4, "foregroundcolor", [1 1 1]);

    else
        set(topicBtn5, "backgroundcolor", [0.05 0.35 0.55]);
        set(topicBtn5, "foregroundcolor", [1 1 1]);
    end

endfunction

//DEFAULT TOPIC
show_topic(1);
